### ISSUE TITLE
Steffi's feedback

### ISSUE THREAD

**Issue by steffilazerte** [ropensci-review-tools/dashboard#12]
Hi @mpadge, you asked for feedback so here you have it! Bear in mind, I'm not 100% sure of the goal of this project, so my feedback may not always align with what you're trying to achieve.

First, this is a super snappy dashboard! It was easy to navigate, and even for someone like me who is relatively unfamiliar with the nitty gritty of these details, it was really straightforward to figure it out. The search was really cool in that you could actually search the whole dashboard for a specific review and find them!

**Formatting nitty gritty**
- It could be nice if the navbar at the top was sticky and didn't disappear when you scroll down (but that's possibly just a personal preference, it returns quickly when you start to scroll up again)

**rOpenSci Editors Page**
- Could `inactive_for` be clarified? Is it a problem that editors are inactive? It almost seems to imply that they're supposed to be always active. Consider `last_active` instead? Possibly just my perspective as someone not familiar with the system.
- Would it be possible to facet or use tabs for the figures, so that there could be two figures? One would show just the "Available" editors and then the second would show them all. This would allow you to see at a glance whom to pick of the available editors, without having to scroll back to the top to remind you of which ones were actually available.
- Relatedly, would it be possible to sort the editors in the figure to descend in the order of available, and least amount of load in the past 1-2 months? That would make it even easier to just look at the top few and pick one quickly? Not sure if there's more nuance that I'm missing, however.
- The names in this figure look overplotted. I assume they're plotted with the same dataset that has the activity data, so there are 100's of text labels for each editor making them look a bit pixelated. This is purely a nit-picky detail, but since everything else looks so nice... 😁 
- I saw #8, and thought that [ggiraph](https://davidgohel.github.io/ggiraph/) might be helpful?

**Editor Reviews**
- I love your use of colour in the figures and tables everywhere. Would there be a use for colour-coding the `state` column for OPEN/CLOSED to make that jump a bit better, or is that not useful?

**Software Review Overview**
- Consider defining the 'grey' colour in the table of urgency
- Is it worth putting this page after "rOpenSci Editors"? It seems like the "rOpenSci Editors" and the "Software Review Overview" pages are the two most important with respect to Peer Review tasks. The other two look more like general info/background.
- Is it worth putting a summary table at the top collecting all reasonably urgent issues? This way, you could see at a glance what needs to be done, but you still have the full overview later. 

Love the software review history figures, so cool to see how things have been going!

Anyway, I hope this feed back is helpful, let me know if you have any questions or would like clarification!

**Comment by mpadge** [comment]
Thanks so much @steffilazerte for this really useful feedback. I'll convert into concrete tasks next week, and start checking them all off then :rocket: :smile:

**Comment by mpadge** [comment]
Thanks @steffilazerte. I've been incorporating some of your feedback via other issues, and am now getting around to explicitly addressing everything else.

## TODO

### Formatting nitty gritty

- [x] ~~It could be nice if the navbar at the top was sticky and didn't disappear when you scroll down (but that's possibly just a personal preference, it returns quickly when you start to scroll up again)~~ Done.

### rOpenSci Editors Page

- [ ] Could inactive_for be clarified? Is it a problem that editors are inactive? It almost seems to imply that they're supposed to be always active. Consider last_active instead? Possibly just my perspective as someone not familiar with the system.
- [ ] Would it be possible to facet or use tabs for the figures, so that there could be two figures? One would show just the "Available" editors and then the second would show them all. This would allow you to see at a glance whom to pick of the available editors, without having to scroll back to the top to remind you of which ones were actually available.
- [ ] Relatedly, would it be possible to sort the editors in the figure to descend in the order of available, and least amount of load in the past 1-2 months? That would make it even easier to just look at the top few and pick one quickly? Not sure if there's more nuance that I'm missing, however.
- [x] ~~The names in this figure look overplotted. I assume they're plotted with the same dataset that has the activity data, so there are 100's of text labels for each editor making them look a bit pixelated. This is purely a nit-picky detail, but since everything else looks so nice... 😁~~ Done, via next response
- [x] ~~I saw https://github.com/ropensci-review-tools/dashboard/issues/8, and thought that [ggiraph](https://davidgohel.github.io/ggiraph/) might be helpful?~~ Thanks, plots now rendered with ggiraph.

### Editor Reviews

- [ ] I love your use of colour in the figures and tables everywhere. Would there be a use for colour-coding the state column for OPEN/CLOSED to make that jump a bit better, or is that not useful?

### Software Review Overview

- [ ] Consider defining the 'grey' colour in the table of urgency
- [ ] Is it worth putting this page after "rOpenSci Editors"? It seems like the "rOpenSci Editors" and the "Software Review Overview" pages are the two most important with respect to Peer Review tasks. The other two look more like general info/background.
- [ ] Is it worth putting a summary table at the top collecting all reasonably urgent issues? This way, you could see at a glance what needs to be done, but you still have the full overview later.

**Comment by mpadge** [comment]
@steffilazerte Thank you so much for your very considered comments. Implementing all of those changes has improved the dashboard enormously. (And also been a lot of work - see above commit history ...) Please feel free to take a look around [latest version](https://ropensci-review-tools.github.io/dashboard), and provide any further feedback you might have. I'll close this issue for now, but please also feel free to re-open with any additional comments. Thanks again!
